language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install dependencies
  - sudo apt-get install python-pip
  - sudo pip install jinja2

script:
  - make

notifications:
  email:
    - eudoxiahp@gmail.com
